networks:
  stack:
    driver: bridge

volumes:
  grafana-storage: {}
  loki-storage: {}
  prometheus-storage: {}
  alloy-storage: {}

services:

# ---- Media ---

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ${USER_HOME}/Programs/jellyfin-config:/config
      - ${USER_HOME}/Programs/jellyfin-cache:/cache
      - ${MUSIC_DIR}:/media/music
    restart: 'unless-stopped'
    networks:
      - stack

  flaresolverr:
    # not monitored, no need
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York
    ports:
      - "${PORT:-8191}:8191"
    volumes:
      - /var/lib/flaresolverr:/config
    restart: unless-stopped

# ---- Observability Stack -----

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - stack

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-storage:/var/lib/loki
    networks:
      - stack

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - prometheus-storage:/prometheus
    networks:
      - stack

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    restart: unless-stopped
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - alloy-storage:/var/lib/alloy/data
      - /var/log/journal:/var/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ${USER_HOME}/Programs:${USER_HOME}/Programs:ro
    networks:
      - stack
