global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

# removed to try to get alloy to sit btwn exporter and prom
#  - job_name: 'node'
#    static_configs:
#      - targets: ['node-exporter:9100']
